nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.1.cjs

npmPublishRegistry: https://npm.pkg.github.com

npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: ${GITHUB_TOKEN-}
    npmAlwaysAuth: true

npmScopes:
  benjamin-guibert:
    npmRegistryServer: https://npm.pkg.github.com
